name: leguang_guide
description: "乐逛用户引导组件"
version: 0.0.6
homepage: https://www.guopi.xin
repository: https://github.com/error-code/leguang_guide
issue_tracker: https://github.com/error-code/leguang_guide/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# flutter pub publish --server=https://pub.dartlang.org

